#!/bin/sh
PNAME=$1
PSERVER=$2
lpsystem -t bsd 
lpadmin -p $PNAME -s $PSERVER
lpadmin -p $PNAME -I any
cd /etc/lp/fd
for i in download dpost postio postior postprint jpostprint jprconv postreverse; do
 lpfilter -f $i - < $i.fd
done
accept $PNAME
enable $PNAME
#if [ $3 == "default" ]; then
#  lpadmin -d $PNAME #デフォールトプリンタに指定
#fi
